package com.neuedu.dao;

import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

@Mapper
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    /**
     *     更新商品状态
     */
    int updateStatusByProduct(Product product);
    /**
     *     后台----搜索商品，根据商品id 或者 商品名（模糊查询）
     */
    List<Product> selectproductByProductIdAndProductName(@Param(value = "productId")Integer productId,
                                                         @Param(value = "productName")String productName);
    /**
     *     前台---搜索商品，根据商品id 或者 商品名（模糊查询）
     */
    List<Product> selectproductportal(@Param(value = "date")Set<Integer> date,
                                      @Param(value = "keyword")String keyword);
}